# Imagem base do Node
FROM node:20-alpine

# Define o diretório de trabalho
WORKDIR /app

# Copia os manifestos de pacotes
COPY package.json package-lock.json ./

# Instala as dependências. O diretório node_modules será montado
# a partir de um volume no docker-compose.override.yml para performance.
RUN npm install

# Expõe a porta do servidor de desenvolvimento do Angular
EXPOSE 4200