server {
    # O Nginx escutará na porta 80, o padrão para HTTP.
    listen 80;
    server_name localhost; # Em produção, será o seu domínio (ex: esleynathan.com.br)

    # Define o diretório raiz onde os arquivos do Angular estão.
    # Corresponde ao destino da cópia no frontend/Dockerfile.
    root /usr/share/nginx/html;
    index index.html;

    # --- Rota para a API Backend (Reverse Proxy) ---
    # Todas as requisições que começam com /api/ serão encaminhadas
    # para o serviço 'backend' na porta 8000, conforme definido no docker-compose.yml.
    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # --- Rota para a SPA Angular ---
    # Para qualquer outra rota que não seja um arquivo ou diretório existente,
    # sirva o index.html. Isso é essencial para que o roteador do Angular funcione.
    location / {
        try_files $uri $uri/ /index.html;
    }
}