# Generated by Django 5.2.9 on 2025-12-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da tecnologia ou habilidade', max_length=100, unique=True, verbose_name='Nome')),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('devops', 'DevOps'), ('database', 'Database'), ('tools', 'Ferramentas'), ('other', 'Outros')], default='other', help_text='Categoria da habilidade', max_length=20, verbose_name='Categoria')),
                ('proficiency_level', models.CharField(choices=[('basic', 'Básico'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado'), ('expert', 'Expert')], default='intermediate', help_text='Nível de domínio da tecnologia', max_length=20, verbose_name='Nível de proficiência')),
                ('icon', models.ImageField(blank=True, help_text='Logo ou ícone da tecnologia', null=True, upload_to='skills/', verbose_name='Ícone')),
                ('order', models.IntegerField(default=0, help_text='Ordem de exibição', verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
