# Generated by Django 5.2.9 on 2025-12-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do projeto', max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, help_text='URL amigável (gerado automaticamente)', max_length=220, unique=True)),
                ('description', models.CharField(help_text='Resumo do projeto (exibido em cards)', max_length=300, verbose_name='Descrição curta')),
                ('detailed_description', models.TextField(help_text='Descrição completa do projeto', verbose_name='Descrição detalhada')),
                ('image', models.ImageField(blank=True, help_text='Imagem principal do projeto', null=True, upload_to='projects/', verbose_name='Imagem de capa')),
                ('technologies', models.CharField(help_text='Tecnologias usadas (separadas por vírgula). Ex: Django, React, PostgreSQL', max_length=500, verbose_name='Tecnologias')),
                ('github_url', models.URLField(blank=True, help_text='URL do repositório no GitHub', null=True, verbose_name='Link do GitHub')),
                ('live_url', models.URLField(blank=True, help_text='URL do projeto em produção', null=True, verbose_name='Link do projeto')),
                ('featured', models.BooleanField(default=False, help_text='Exibir na página inicial?', verbose_name='Destacar')),
                ('order', models.IntegerField(default=0, help_text='Ordem de exibição (menor número aparece primeiro)', verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
