# Generated by Django 5.2.9 on 2026-01-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('automation', 'Automação'), ('challenges', 'Desafios Técnicos'), ('applications', 'Aplicações')], default='applications', help_text='Categoria do projeto (Automação, Desafios Técnicos, Aplicações)', max_length=20, verbose_name='Categoria'),
        ),
    ]
