# Generated by Django 5.2.9 on 2025-12-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome completo do remetente', max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(help_text='E-mail do remetente', max_length=254, verbose_name='E-mail')),
                ('subject', models.CharField(help_text='Assunto da mensagem', max_length=300, verbose_name='Assunto')),
                ('message', models.TextField(help_text='Conteúdo da mensagem', verbose_name='Mensagem')),
                ('read', models.BooleanField(default=False, help_text='Mensagem foi lida?', verbose_name='Lida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Recebida em')),
            ],
            options={
                'verbose_name': 'Mensagem de Contato',
                'verbose_name_plural': 'Mensagens de Contato',
                'ordering': ['-created_at'],
            },
        ),
    ]
